server:
  bind_addr: "0.0.0.0"
  bind_port: 7000
  
web:
  bind_addr: "0.0.0.0"
  bind_port: 8080
  
auth:
  token: "tunnel-secret-token-2026"
  
performance:
  max_connections: 10000
  pool_size: 1000
  read_buffer_size: 8192
  write_buffer_size: 8192
  worker_pool_size: 500
